language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server
before_script:
  - sudo apt-get install autoconf
  - tests/travis/install-apcu.sh
  - tests/travis/install-memcache.sh
  - phpenv config-add tests/travis/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add tests/travis/apc.ini
  - composer install --dev
  - scripts/cm.php app generate-config-local resources/config/local.ci.json
  - scripts/cm.php app set-deploy-version
script: phpunit
notifications:
  email: false
